export const theme = {
    colors:{
        primary:"#2a4d50",
        secondary:"#ddf0ff",
        tertiary:"#ff7754",
        gray:"#83829a",
        offWhite:'#f3f4f8',
        white:"#fff",
        black:"#000"
    },
    sizes:{
        xSmall:10,
        small:12,
        medium:16,
        large:20,
        xLarge:24,
        xxLarge:44,
    }
}